### ISSUE TITLE
Error in open.connection(con, "rb") : cannot open the connection

### ISSUE THREAD

**Issue by dm8000** [lfranzen/scwat-st#1]
Hello

I am trying to reproduce the code and got the following error on block 179-185 in the visium_baseline.main_analysis.Rmd file.

Here is the traceback

```
Error in open.connection(con, "rb") : cannot open the connection
12.
open.connection(con, "rb")
11.
open(con, "rb")
10.
parse_con(txt, bigint_as_char)
9.
parseJSON(txt, bigint_as_char)
8.
parse_and_simplify(json, simplifyVector = simplifyVector, ...)
7.
parse_json(file(path), simplifyVector = simplifyVector, ...)
6.
read_json(f)
5.
FUN(X[[i]], ...)
4.
lapply(X = X, FUN = FUN, ...)
3.
sapply(infotable[, "json"], function(f) { read_json(f)$tissue_hires_scalef })
2.
scaleVisium %||% sapply(infotable[, "json"], function(f) { read_json(f)$tissue_hires_scalef })
1.
InputFromTable(infotable = infoTable, min.gene.count = 100, min.gene.spots = 5, min.spot.count = 200, platform = "Visium")

```

**Comment by lfranzen** [comment]
Hi! Not sure I recognise the error entirely, however it looks a bit like the file paths might be the issue? Could you double check to make sure the paths in your `infoTable` is pointing to your data files correctly?

**Comment by dm8000** [comment]
Thank you for the reply @lfranzen 


the `infotable` is as original. I imagined it could be a path problem as I did not edit anything, but I assumed it was working fine as the `Sample meta data  ` block loaded the table without problems

```

```{r create_infotable}
sample_select_ids <- metadata_selected[, "novaseq_id"]
data_proc <- "trimmed"
sample_dirs_all <- c()
sample_names_all <- c()
for (s in sample_select_ids){
  message("Fetching data path for sample ", s)
  sample_dirs <- grep(pattern = s, x = list.dirs(path = file.path(DIR_DATA), recursive = F, full.names = T), value = T)
  sample_dirs <- grep(pattern = data_proc, x = sample_dirs, value = T)
  sample_dirs_all <- c(sample_dirs_all, sample_dirs)
  
  sample_names <- grep(pattern = s, x = list.dirs(path = file.path(DIR_DATA), recursive = F, full.names = F), value = T)
  sample_names <- grep(pattern = data_proc, x = sample_names, value = T)
  sample_names_all <- c(sample_names_all, sample_names)
}

data_dirs <- paste0(sample_dirs_all, "/filtered_feature_bc_matrix.h5")
spot_dirs <- paste0(sample_dirs_all, "/spatial/tissue_positions_list.csv")
img_dirs <- paste0(sample_dirs_all, "/spatial/tissue_hires_image.png")
img_scale_dirs <- paste0(sample_dirs_all, "/spatial/scalefactors_json.json")

infoTable <- data.frame(samples = data_dirs,
                        spotfiles = spot_dirs,
                        imgs = img_dirs,
                        json = img_scale_dirs,
                        metadata_selected, 
                        stringsAsFactors = F)
```
I downloaded the data and put it in the data folder, but maybe I did not structured it correctly?
Here is what the data folder looks like

```
~/Documents/visiumadipocyte/scwat-st/data/visium$ ls
S41_trimmed  S46_trimmed  S51_trimmed  se-object.visium_baseline.rds.zip
S42_trimmed  S47_trimmed  S52_trimmed  se-object.visium_insulin.rds.zip
S43_trimmed  S48_trimmed  S53_trimmed  stereoscope_210322.zip
S44_trimmed  S49_trimmed  S54_trimmed  visium_sample_metadata.tsv
S45_trimmed  S50_trimmed  S55_trimmed

```
Neatly organized code btw

**Comment by lfranzen** [comment]
> Thank you for the reply @lfranzen
> 
> the `infotable` is as original. I imagined it could be a path problem as I did not edit anything, but I assumed it was working fine as the `Sample meta data ` block loaded the table without problems
> 
> ```
> 
> ```{r create_infotable}
> sample_select_ids <- metadata_selected[, "novaseq_id"]
> data_proc <- "trimmed"
> sample_dirs_all <- c()
> sample_names_all <- c()
> for (s in sample_select_ids){
>   message("Fetching data path for sample ", s)
>   sample_dirs <- grep(pattern = s, x = list.dirs(path = file.path(DIR_DATA), recursive = F, full.names = T), value = T)
>   sample_dirs <- grep(pattern = data_proc, x = sample_dirs, value = T)
>   sample_dirs_all <- c(sample_dirs_all, sample_dirs)
>   
>   sample_names <- grep(pattern = s, x = list.dirs(path = file.path(DIR_DATA), recursive = F, full.names = F), value = T)
>   sample_names <- grep(pattern = data_proc, x = sample_names, value = T)
>   sample_names_all <- c(sample_names_all, sample_names)
> }
> 
> data_dirs <- paste0(sample_dirs_all, "/filtered_feature_bc_matrix.h5")
> spot_dirs <- paste0(sample_dirs_all, "/spatial/tissue_positions_list.csv")
> img_dirs <- paste0(sample_dirs_all, "/spatial/tissue_hires_image.png")
> img_scale_dirs <- paste0(sample_dirs_all, "/spatial/scalefactors_json.json")
> 
> infoTable <- data.frame(samples = data_dirs,
>                         spotfiles = spot_dirs,
>                         imgs = img_dirs,
>                         json = img_scale_dirs,
>                         metadata_selected, 
>                         stringsAsFactors = F)
> ```
> 
> I downloaded the data and put it in the data folder, but maybe I did not structured it correctly? Here is what the data folder looks like
> 
> ```
> ~/Documents/visiumadipocyte/scwat-st/data/visium$ ls
> S41_trimmed  S46_trimmed  S51_trimmed  se-object.visium_baseline.rds.zip
> S42_trimmed  S47_trimmed  S52_trimmed  se-object.visium_insulin.rds.zip
> S43_trimmed  S48_trimmed  S53_trimmed  stereoscope_210322.zip
> S44_trimmed  S49_trimmed  S54_trimmed  visium_sample_metadata.tsv
> S45_trimmed  S50_trimmed  S55_trimmed
> ```
> 
> Neatly organized code btw

I see, that code should hopefully work, or at least I thought I made it so that it should work! However could you print out one example row from the `infoTable` and make sure the entire path are pointing to the correct locations? Especially the `scalefactors_json.json` files since it seems that's what the initial error was complaining about

**Comment by dm8000** [comment]
Hello @lfranzen 


It seems it could have been a problem with my environment, as the code seems to run smoothly after I restarted. I ran into another problem though, which I will open another issue. 

Thank you for the help!
