### ISSUE TITLE
no "se-object.visium_baseline_ori.rds"

### ISSUE THREAD

**Issue by dm8000** [lfranzen/scwat-st#2]
I ran into another problem from the block in line 322

```{r read_ori_se, include=FALSE}
#' Read in original se object in case minor random changes in the SCTransform/ICA/UMAP has occurred
se <- readRDS(file = file.path(DIR_DATA, "se-object.visium_baseline_ori.rds"))
se@tools$Staffli@imgs <- infoTable$imgs
```

The error is

```
Error in gzfile(file, "rb") : cannot open the connection
2.
gzfile(file, "rb")
1.
readRDS(file = file.path(DIR_DATA, "se-object.visium_baseline_ori.rds"))
```

I see no rds called `se-object.visium_baseline_ori.rds`, in the data folder, nor in the [downloadable data](https://data.mendeley.com/datasets/3bs5f8mvbs/1). I also see no `saveRDS()` command upstream, so I assume it is not created by the script. There were no errors or warnings previous to this. There is a .zip file called `se-object.visium_baseline.rds.zip` though, which I am unsure if it is the same. However, when I extract it, it creates a folder instead of a rds file. Is this working as intended?

**Comment by lfranzen** [comment]
Hi! Sorry, that object and code is a remnant from when I was working on the analysis. You can ignore that :) The se-`object.visium_baseline.rds` object is the one you want to work with if you want to look into the exact same results as I obtained when performing the analyses. Hopefully the R object should be in that folder you receive when unzipping the .zip file – let me know if that's not the case and I'll look into it!

Cheers
Lovisa

**Comment by dm8000** [comment]
Thanks!!
